### ISSUE TITLE
Failed to install on MacOS

### ISSUE THREAD

**Issue by dongxuDX** [videlec/pplpy#36]
Hi,

Thanks for the tool!

When I tried to install using the command:
 ```pip install pplpy```
I got the following error:
```$ pip install pplpy==0.7
Collecting pplpy==0.7
  Using cached pplpy-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pplpy.egg-info
    writing pip-egg-info/pplpy.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/pplpy.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/pplpy.egg-info/requires.txt
    writing top-level names to pip-egg-info/pplpy.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/pplpy.egg-info/SOURCES.txt'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        if MPZ_Check(c):
            coeff = <mpz> c
        else:
            coeff = mpz(c)
    
        return PPL_Coefficient(coeff.z)
                             ^
    ------------------------------------------------------------
    
    ppl/linear_algebra.pyx:57:26: no suitable method found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lt/187_r3zj2533ntk44_7d569c0000gn/T/pip-build-tb3o2cal/pplpy/setup.py", line 117, in <module>
        cmdclass = {'build_ext': build_ext, 'test': TestCommand}
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 278, in run
        self.find_sources()
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
        mm.run()
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 524, in run
        self.add_defaults()
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
        sdist.add_defaults(self)
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/lt/187_r3zj2533ntk44_7d569c0000gn/T/pip-build-tb3o2cal/pplpy/setup.py", line 28, in finalize_options
        self.distribution.ext_modules, include_path=sys.path)
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
        cythonize_one(*args)
      File "/anaconda3/envs/HyPyFlow/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: ppl/linear_algebra.pyx
    Compiling ppl/linear_algebra.pyx because it changed.
    Compiling ppl/mip_problem.pyx because it changed.
    Compiling ppl/polyhedron.pyx because it changed.
    Compiling ppl/generator.pyx because it changed.
    Compiling ppl/constraint.pyx because it changed.
    [1/5] Cythonizing ppl/constraint.pyx
    [2/5] Cythonizing ppl/generator.pyx
    [3/5] Cythonizing ppl/linear_algebra.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/lt/187_r3zj2533ntk44_7d569c0000gn/T/pip-build-tb3o2cal/pplpy/```

```

I already changed CFLAGS as indicated:
```$ echo $CFLAGS
-I/usr/local/Cellar/gmp/6.1.2/include/ -L/usr/local/Cellar/gmp/6.1.2/lib/ -I/usr/local/Cellar/ppl/1.2/include/ -L/usr/local/Cellar/ppl/1.2/lib/
```
I am running Python 3.6, pip 9.0.3, gmp 6.1.2, ppl 1.2 on MacOS 10.13.3 High Sierra.

I will be appreciated if, by any chance, you can help me out.
Thanks a lot.

**Comment by videlec** [comment]
It seems to me that you are strangly mixing anaconda with system library (though it might not be the origin of the problem).  Could you check
- your Cython version
- whether the Python package gmpy2 is installed

**Comment by yi-ji** [comment]
@videlec 
I am having the same problem on macOS 10.12. All dependencies satisfied,
Cython version: 0.28.1
 gmpy2 is installed at `/usr/local/lib/python2.7/site-packages`

Thank you for your kind help!

My error message is:
```
00:35:46 jiyi: pip install pplpy
Collecting pplpy
  Using cached https://files.pythonhosted.org/packages/ca/d3/1629e95997068c129e3a5235fd32a39e4fc39faca892cf9a2da11f842fb9/pplpy-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pplpy.egg-info
    writing requirements to pip-egg-info/pplpy.egg-info/requires.txt
    writing pip-egg-info/pplpy.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pplpy.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pplpy.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pplpy.egg-info/SOURCES.txt'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        if MPZ_Check(c):
            coeff = <mpz> c
        else:
            coeff = mpz(c)

        return PPL_Coefficient(coeff.z)
                             ^
    ------------------------------------------------------------

    ppl/linear_algebra.pyx:57:26: no suitable method found
    /usr/local/lib/python2.7/site-packages/cysignals/signals.pxd: cannot find cimported module 'cysignals.__init__'
    Compiling ppl/linear_algebra.pyx because it changed.
    Compiling ppl/mip_problem.pyx because it changed.
    Compiling ppl/polyhedron.pyx because it changed.
    Compiling ppl/generator.pyx because it changed.
    Compiling ppl/constraint.pyx because it changed.
    [1/5] Cythonizing ppl/constraint.pyx
    [2/5] Cythonizing ppl/generator.pyx
    [3/5] Cythonizing ppl/linear_algebra.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wy/rzll0f4j3ln0c9p4l93v080h0000gn/T/pip-build-g5SGgQ/pplpy/setup.py", line 117, in <module>
        cmdclass = {'build_ext': build_ext, 'test': TestCommand}
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 278, in run
        self.find_sources()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
        mm.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 524, in run
        self.add_defaults()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/wy/rzll0f4j3ln0c9p4l93v080h0000gn/T/pip-build-g5SGgQ/pplpy/setup.py", line 28, in finalize_options
        self.distribution.ext_modules, include_path=sys.path)
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
        cythonize_one(*args)
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: ppl/linear_algebra.pyx

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wy/rzll0f4j3ln0c9p4l93v080h0000gn/T/pip-build-g5SGgQ/pplpy/
```

@dongxuDX could you share your solution if have fixed this problem? thank you!

**Comment by videlec** [comment]
@dongxuDX @yi-ji 
Could you please try installing the development version
```
pip install git+https://github.com/videlec/pplpy/ --verbose
```

**Comment by videlec** [comment]
Just to be sure: did you install the source version of `gmpy2` with something like
```
pip install gmpy2==2.1.0a1 --no-binary ":all:" [--user]
```

**Comment by yi-ji** [comment]
@videlec Thank you for your kind tips!
Seems I did't install gmpy2 correctly as you instructed... so after i have done it and fixed some other irrelevant problems, now when i try to import ppl i get:

```
15:02:13 jiyi: python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ppl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ppl/__init__.py", line 130, in <module>
    from .linear_algebra import (
  File "ppl/constraint.pxd", line 9, in init ppl.linear_algebra
    cdef class Constraint(object):
  File "ppl/constraint.pyx", line 25, in init ppl.constraint
AttributeError: 'module' object has no attribute '_C_API'  
```

(`import gmpy2` has no problem)

could you give some suggestion about this? thank you for your time!

**Comment by videlec** [comment]
What is your compiler? Do you use `gcc` or `clang`?

**Comment by yi-ji** [comment]
I am using clang:
```
00:24:28 jiyi: gcc
clang: error: no input files
```

and I found that I can import ppl and ran sample code successfully only when my current dir is `/usr/local/lib/python2.7/site-packages` where ppl is installed.

I am using brew python and pip (in `/usr/local/Cellar/...`). I also tried to install from your latest commit, but seems nothing changed for me..

**Comment by videlec** [comment]
@yi-ji this is even more weird! clang compilation does not work for me (as well as on Ubuntu, #37).

> and I found that I can import ppl and ran sample code successfully only when
> my current dir is /usr/local/lib/python2.7/site-packages where ppl is installed.

Here I believe you meant `pplpy` instead of `ppl` here. What about setting `LD_LIBRARY_PATH` before launching python via
```
$ LD_LIBRARY_PATH="/usr/local/lib/python2.7/site-packages" python
```
If it appears to work (from any directory), could you also give me the complete output of
```
$ ls /usr/local/lib/python2.7/site-packages/ppl/
```
And depending whether you see files ending with `.so` or with `.dylib` there send me the result of
```
$ otool -L /usr/local/lib/python2.7/site-packages/ppl/FILE
```
where `FILE` has to be replaced with each of the `.so` or `.dylib` file in the repository.

**Comment by yi-ji** [comment]
well I don't know much about clang problem.. FYI
```
00:47:45 jiyi: clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Yes, I mean I can `import ppl ` in where `pplpy` is installed.

Sadly doing `export LD_LIBRARY_PATH="/usr/local/lib/python2.7/site-packages"` does not help, still same `AttributeError: 'module' object has no attribute '_C_API'`

And
```
00:50:11 jiyi: ls /usr/local/lib/python2.7/site-packages/ppl/
__init__.py		constraint.so		linear_algebra.pxd	mip_problem.so		ppl_decl.pxd
__init__.pyc		generator.pxd		linear_algebra.so	polyhedron.pxd		ppl_shim.hh
constraint.pxd		generator.so		mip_problem.pxd		polyhedron.so
```

and
```
 00:51:32 jiyi: otool -L /usr/local/lib/python2.7/site-packages/ppl/ANY-FILE-IS-SAME.so
/usr/local/lib/python2.7/site-packages/ppl/generator.so:
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	/usr/local/opt/gmp/lib/libgmpxx.4.dylib (compatibility version 10.0.0, current version 10.2.0)
	/usr/local/opt/ppl/lib/libppl.14.dylib (compatibility version 15.0.0, current version 15.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
```

**Comment by videlec** [comment]
It might be that you have two versions of `gmpy2` installed on your system in different repos. Could you try uninstalling *twice* `gmpy2` (with `pip uninstall gmpy2`). The first time you should see a message asking you whether you want to uninstall the version in `/usr/local/lib/python2.7/` (answer YES). The second time it should not work.

**Comment by videlec** [comment]
Could you also post the output of
```
$ python -c "import sys; print(sys.path)"
```
(assuming that `python` does launch the Python interpreter)

**Comment by videlec** [comment]
As well as
```
$ python -c "import gmpy2; print(gmpy2.__file__)"
```
(try this command from your home directory and also from `/usr/local/lib/python2.7/`)

**Comment by videlec** [comment]
@yi-ji Sorry for letting you uninstall the gmpy2 (you can pip install it again now :-).

The output of
```
$ python -c "import sys; print(sys.path)"
$ python -c "import gmpy2; print(gmpy2.__file__)"
```
tell you the problem. In `sys.path` the `/usr/local/lib/` does appear **after** `/Library/Python/2.7`. This list corresponds to the search path of python libraries (in order). As a consequence when you load `gmpy2` the one that is used is the one from `/Library/Python/2.7` and not the one from `/usr/local/lib` that was installed with `pip`.

I see two possible solutions

- either you remove the gmpy2 from `/Library/Python/2.7` (do you happen to know how this was installed on your system?)

- or you modify `sys.path` so that `/usr/local/lib` appears before `/Library/Python/2.7`. This can be done with the unreadable one-line command
```
$ python
>>> import sys
>>> sys.path.insert(0, sys.path.pop(sys.path.index('/usr/local/lib/python2.7/site-packages')))
```
(I am not sure whether this second solution does work but it would be less intrusive). The above should be done **before** importing `gmpy2` or `ppl`.

**Comment by dongxuDX** [comment]
@videlec Sorry for the (super) late response!

I switched to an interpreter outside anaconda. Then tried to uninstall gmpy2, by
`pip3 uninstall gmpy2`

and then re-install with
`pip3 install gmpy2==2.1.0a1 --no-binary ":all:" `.
Now I am able to install pplpy with no issue using
`pip3 install pplpy`

Thanks for the follow-up and kind tips. And please feel free to close the issue.
